apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: oy6he9458-nodejs-gitops
  description: This is GitOps manifest for oy6he9458-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=oy6he9458-nodejs
    backstage.io/kubernetes-id: oy6he9458-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: oy6he9458-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:oy6he9458-nodejs
