apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: oy6he9458-nodejs
  janus-idp.io/tekton: oy6he9458-nodejs
  backstage.io/kubernetes-id: oy6he9458-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oy6he9458-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
