apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: oy6he9458-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oy6he9458-nodejs 
  name: oy6he9458-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: oy6he9458-nodejs 
